# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img_url',
            field=models.CharField(default='fake.url', max_length=128),
            preserve_default=False,
        ),
    ]
