# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_auto_20170923_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
