# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-10 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_item_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cannabinoids',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='item',
            name='genetics',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='item',
            name='terpenes',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='img_url',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
